# Prod development configuration.
# Use in combination with Authentication profiles: IN-MEMORY, LDAP, JDBC.

# Logging configuration
logging:
  level:
    root: WARN
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.security.oauth2: WARN
    org.springframework.boot.autoconfigure: INFO

# Spring configurations
spring:
  # LDAP configuration
  ldap:
    embedded:
      ldif: classpath:test-server.ldif
      base-dn: dc=springframework,dc=org
      port: 8389