# Logging configuration
logging:
  level:
    root: WARN
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.security.oauth2: WARN
    org.springframework.boot.autoconfigure: INFO
